name: rc / Build

on:
  push:
    branches:
      - wkf-test
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel: ["6.8.0-63-generic", "6.11.0-24-generic"]

    steps:
      - name: Show current kernel version
        run: uname -r

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kernel headers
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-headers-${{ matrix.kernel }} build-essential

      - name: Build kernel module
        run: |
          make CONFIG_SIMPLE_TRACE=m CONFIG_SIMPLE_LOOKUP_NAME=m EXTRA_CFLAGS="-DCONFIG_SIMPLE_TRACE_LOGSIZE_SHIFT=12" CONFIG_SIMPLE_TRACE_USE_TIME=y
          mv simple_trace.ko simple_trace-${{ matrix.kernel }}.ko
          mv simple_lookup_name.ko simple_lookup_name-${{ matrix.kernel }}.ko

      - name: Upload module as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-modules
          path: |
            simple_trace-*.ko
            simple_lookup_name-*.ko
