name: rc / Build

on:
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Linux Kernel Version (e.g., v5.15.0)'
        required: true
        default: 'v6.15'
      arch:
        description: 'Architecture (e.g., x86_64, arm64)'
        required: true
        default: 'x86_64'
  push:
    branches:
      - wkf-test
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show current kernel version
        run: uname -r

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc git build-essential libncurses-dev flex bison libssl-dev libelf-dev bc cpio xz-utils curl

      - name: Clone Linux kernel
        run: |
          git clone https://github.com/torvalds/linux.git kernel --depth 1 --branch ${{ github.event.inputs.kernel_version || 'v6.15' }} 
          cd kernel
          echo "Linux kernel $(make kernelversion) cloned"
          
      - name: Build kernel module
        run: |
          KERNEL_DIR=./kernel BRANCH=rc sh -c "$(curl -fsSL https://github.com/Licay/Simple-Trace/raw/refs/heads/rc/tools/setup.sh)"
          make -C kernel O=out defconfig
          echo "CONFIG_SIMPLE_TRACE=m" >> kernel/.config
          echo "CONFIG_SIMPLE_TRACE_LOGSIZE_SHIFT=12" >> kernel/.config
          echo "CONFIG_SIMPLE_TRACE_USE_TIME=y" >> kernel/.config
          echo "CONFIG_SIMPLE_LOOKUP_NAME=m" >> kernel/.config
          make -C kernel O=out -j`nproc`
          find . -name "simple*.ko"
          cp `find . -name "simple*.ko"` ./
          mv simple_trace.ko simple_trace-${{ matrix.kernel }}.ko
          mv simple_lookup_name.ko simple_lookup_name-${{ matrix.kernel }}.ko

      - name: Upload module as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-modules
          path: |
            simple_trace*.ko
            simple_lookup_name*.ko
